/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import services.SummaryService;
import services.AnalysisService;
import services.SearchService;
import services.KeywordService;


/**
 *
 * @author rafaelc3127
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    
    private SummaryService summaryService;
    private AnalysisService analysisService;
    private SearchService searchService;
    private KeywordService keywordService;

    /**
     * Creates new form MainFrame
     */
    public MainFrame(
            SummaryService summaryService,
            AnalysisService analysisService,
            SearchService searchService,
            KeywordService keywordService
    ) {
        initComponents();
        
        this.summaryService = summaryService;
        this.analysisService = analysisService;
        this.searchService = searchService;
        this.keywordService = keywordService;
    }
    
    /**
     * Resets the Add Summary panel to its initial state
     */
    private void resetAddSummaryPanel() {
        // Clear preview text
        addSummaryPreviewTextArea.setText("");
        
        // Hide preview components
        addSummaryPreviewTitleLabel.setVisible(false);
        addSummaryPreviewTextArea.setVisible(false);
        addSummaryConfirmButton.setVisible(false);
        addSummaryConfirmButton.setEnabled(false);
        
        // Clear stored filepath
        addSummaryConfirmButton.putClientProperty("selectedFilePath", null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        addSummaryPanel = new javax.swing.JPanel();
        addSummaryTitleLabel = new javax.swing.JLabel();
        addSummarySelectFileButton = new javax.swing.JButton();
        addSummarySeparator1 = new javax.swing.JSeparator();
        addSummaryPreviewTitleLabel = new javax.swing.JLabel();
        addSummaryPreviewTextScrollPane = new javax.swing.JScrollPane();
        addSummaryPreviewTextArea = new javax.swing.JTextArea();
        addSummaryConfirmButton = new javax.swing.JButton();
        analyzeSummaryPanel = new javax.swing.JPanel();
        searchKeywordPanel = new javax.swing.JPanel();
        searchAuthorPanel = new javax.swing.JPanel();
        listKeywordPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión de Artículos Científicos");
        setBackground(new java.awt.Color(255, 255, 255));

        headerPanel.setBackground(new java.awt.Color(102, 126, 234));
        headerPanel.setPreferredSize(new java.awt.Dimension(1600, 40));

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("📚 Sistema de Gestión de Artículos Científicos");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        headerPanel.add(titleLabel);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        addSummaryPanel.setBackground(new java.awt.Color(255, 255, 255));

        addSummaryTitleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        addSummaryTitleLabel.setForeground(new java.awt.Color(51, 51, 51));
        addSummaryTitleLabel.setText("Agregar Resumen");

        addSummarySelectFileButton.setBackground(new java.awt.Color(220, 220, 220));
        addSummarySelectFileButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addSummarySelectFileButton.setText("📂 Seleccionar Archivo .txt");
        addSummarySelectFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSummarySelectFileButtonActionPerformed(evt);
            }
        });

        addSummaryPreviewTitleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addSummaryPreviewTitleLabel.setForeground(new java.awt.Color(51, 51, 51));
        addSummaryPreviewTitleLabel.setText("📋 Vista Previa del Resumen:");

        addSummaryPreviewTextArea.setEditable(false);
        addSummaryPreviewTextArea.setBackground(new java.awt.Color(255, 255, 255));
        addSummaryPreviewTextArea.setColumns(50);
        addSummaryPreviewTextArea.setLineWrap(true);
        addSummaryPreviewTextArea.setRows(12);
        addSummaryPreviewTextArea.setWrapStyleWord(true);
        addSummaryPreviewTextScrollPane.setViewportView(addSummaryPreviewTextArea);

        addSummaryConfirmButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addSummaryConfirmButton.setForeground(new java.awt.Color(102, 126, 234));
        addSummaryConfirmButton.setText("✅ Confirmar y Agregar");
        addSummaryConfirmButton.setEnabled(false);
        addSummaryConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSummaryConfirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addSummaryPanelLayout = new javax.swing.GroupLayout(addSummaryPanel);
        addSummaryPanel.setLayout(addSummaryPanelLayout);
        addSummaryPanelLayout.setHorizontalGroup(
            addSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSummaryPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(addSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSummaryConfirmButton)
                    .addGroup(addSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addSummaryPreviewTitleLabel)
                        .addComponent(addSummarySelectFileButton)
                        .addComponent(addSummaryTitleLabel)
                        .addComponent(addSummarySeparator1)
                        .addComponent(addSummaryPreviewTextScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)))
                .addContainerGap(931, Short.MAX_VALUE))
        );
        addSummaryPanelLayout.setVerticalGroup(
            addSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSummaryPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(addSummaryTitleLabel)
                .addGap(18, 18, 18)
                .addComponent(addSummarySelectFileButton)
                .addGap(27, 27, 27)
                .addComponent(addSummarySeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSummaryPreviewTitleLabel)
                .addGap(26, 26, 26)
                .addComponent(addSummaryPreviewTextScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(addSummaryConfirmButton)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("➕ Agregar Resumen", addSummaryPanel);

        analyzeSummaryPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout analyzeSummaryPanelLayout = new javax.swing.GroupLayout(analyzeSummaryPanel);
        analyzeSummaryPanel.setLayout(analyzeSummaryPanelLayout);
        analyzeSummaryPanelLayout.setHorizontalGroup(
            analyzeSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1588, Short.MAX_VALUE)
        );
        analyzeSummaryPanelLayout.setVerticalGroup(
            analyzeSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("📊 Analizar Resumen", analyzeSummaryPanel);

        searchKeywordPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout searchKeywordPanelLayout = new javax.swing.GroupLayout(searchKeywordPanel);
        searchKeywordPanel.setLayout(searchKeywordPanelLayout);
        searchKeywordPanelLayout.setHorizontalGroup(
            searchKeywordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1588, Short.MAX_VALUE)
        );
        searchKeywordPanelLayout.setVerticalGroup(
            searchKeywordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("🔍 Buscar Keyword", searchKeywordPanel);

        searchAuthorPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout searchAuthorPanelLayout = new javax.swing.GroupLayout(searchAuthorPanel);
        searchAuthorPanel.setLayout(searchAuthorPanelLayout);
        searchAuthorPanelLayout.setHorizontalGroup(
            searchAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1588, Short.MAX_VALUE)
        );
        searchAuthorPanelLayout.setVerticalGroup(
            searchAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("👤 Buscar Autor", searchAuthorPanel);

        listKeywordPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout listKeywordPanelLayout = new javax.swing.GroupLayout(listKeywordPanel);
        listKeywordPanel.setLayout(listKeywordPanelLayout);
        listKeywordPanelLayout.setHorizontalGroup(
            listKeywordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1588, Short.MAX_VALUE)
        );
        listKeywordPanelLayout.setVerticalGroup(
            listKeywordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("📋 Listar Keywords", listKeywordPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSummarySelectFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSummarySelectFileButtonActionPerformed
       // Create file chooser with filter for .txt files
       javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
       fileChooser.setDialogTitle("Seleccionar Archivo de Resumen");
       fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
           "Archivos de texto (.txt)", "txt"
       ));
       
       // Set initial directory to data/resumenes if exists
       java.io.File dataDir = new java.io.File("data/resumenes");
       if (dataDir.exists()) {
           fileChooser.setCurrentDirectory(dataDir);
       }
       
       int result = fileChooser.showOpenDialog(this);
       
       if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
           java.io.File selectedFile = fileChooser.getSelectedFile();
           String filepath = selectedFile.getAbsolutePath();
           
           try {
               // Parse the file to get Summary details
               models.Summary summary = io.SummaryParser.parseFromFile(filepath);
               
               // Check if summary already exists
               if (summaryService.summaryExists(summary.getTitle())) {
                   javax.swing.JOptionPane.showMessageDialog(
                       this,
                       "Este resumen ya existe en el sistema:\n\"" + summary.getTitle() + "\"",
                       "Resumen Duplicado",
                       javax.swing.JOptionPane.WARNING_MESSAGE
                   );
                   return;
               }
               
               // Build preview text
               StringBuilder preview = new StringBuilder();
               preview.append("📄 TÍTULO:\n");
               preview.append(summary.getTitle()).append("\n\n");
               
               preview.append("👥 AUTORES:\n");
               basicdatastructures.LinkedList<String> authors = summary.getAuthors();
               basicdatastructures.Node<String> authorNode = authors.getHead();
               while (authorNode != null) {
                   preview.append("  • ").append(authorNode.getData()).append("\n");
                   authorNode = authorNode.getNext();
               }
               preview.append("\n");
               
               preview.append("🔑 PALABRAS CLAVE:\n");
               basicdatastructures.LinkedList<String> keywords = summary.getKeywords();
               basicdatastructures.Node<String> keywordNode = keywords.getHead();
               while (keywordNode != null) {
                   preview.append("  • ").append(keywordNode.getData()).append("\n");
                   keywordNode = keywordNode.getNext();
               }
               preview.append("\n");
               
               preview.append("📝 RESUMEN:\n");
               String body = summary.getBody();
               String bodyPreview = body.length() > 300 
                   ? body.substring(0, 300) + "..." 
                   : body;
               preview.append(bodyPreview);
               
               // Update UI - usando jTextArea1 que está dentro del scrollpane
               addSummaryPreviewTextArea.setText(preview.toString());
               addSummaryPreviewTextArea.setCaretPosition(0); // Scroll to top
               
               // Show preview components
               addSummaryPreviewTitleLabel.setVisible(true);
               addSummaryConfirmButton.setEnabled(true);
               
               // Store filepath in button's client property for later use
               addSummaryConfirmButton.putClientProperty("selectedFilePath", filepath);
               
           } catch (java.io.IOException e) {
               javax.swing.JOptionPane.showMessageDialog(
                   this,
                   "Error al leer el archivo:\n" + e.getMessage(),
                   "Error de Lectura",
                   javax.swing.JOptionPane.ERROR_MESSAGE
               );
               logger.log(java.util.logging.Level.SEVERE, "Error parsing summary file", e);
           } catch (Exception e) {
               javax.swing.JOptionPane.showMessageDialog(
                   this,
                   "Error al procesar el archivo:\n" + e.getMessage(),
                   "Error",
                   javax.swing.JOptionPane.ERROR_MESSAGE
               );
               logger.log(java.util.logging.Level.SEVERE, "Error processing summary", e);
           }
       } 
    }//GEN-LAST:event_addSummarySelectFileButtonActionPerformed

    private void addSummaryConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSummaryConfirmButtonActionPerformed
        // Get the stored filepath from button's client property
        String filepath = (String) addSummaryConfirmButton.getClientProperty("selectedFilePath");
        
        if (filepath == null || filepath.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "No hay archivo seleccionado",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        try {
            // Add summary using the service
            summaryService.addSummary(filepath);
            
            // Show success message
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "✅ Resumen agregado exitosamente al sistema",
                "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
            
            // Reset the panel
            resetAddSummaryPanel();
            
        } catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error al agregar el resumen:\n" + e.getMessage(),
                "Error de I/O",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            logger.log(java.util.logging.Level.SEVERE, "Error adding summary", e);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error inesperado:\n" + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            logger.log(java.util.logging.Level.SEVERE, "Unexpected error adding summary", e);
        }
    }//GEN-LAST:event_addSummaryConfirmButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSummaryConfirmButton;
    private javax.swing.JPanel addSummaryPanel;
    private javax.swing.JTextArea addSummaryPreviewTextArea;
    private javax.swing.JScrollPane addSummaryPreviewTextScrollPane;
    private javax.swing.JLabel addSummaryPreviewTitleLabel;
    private javax.swing.JButton addSummarySelectFileButton;
    private javax.swing.JSeparator addSummarySeparator1;
    private javax.swing.JLabel addSummaryTitleLabel;
    private javax.swing.JPanel analyzeSummaryPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel listKeywordPanel;
    private javax.swing.JPanel searchAuthorPanel;
    private javax.swing.JPanel searchKeywordPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
